### ISSUE TITLE
Update Compiler to support latest EmberJS release (1.0.0-rc.6)

### ISSUE THREAD

**Issue by khalidabuhakmeh** [Myslik/csharp-ember-handlebars#20]
I pulled the latest version from NuGet and using the latest from the EmberJs site and I get this error when enabling compilation.

```
Uncaught Template was precompiled with an older version of Handlebars than the current runtime. Please update your precompiler to a newer version (>= 1.0.0-rc.4) or downgrade your runtime to an older version (<= 1.0.rc.2). 
```

The current workaround is to downgrade, not sure I want to do that for too long.

**Comment by khalidabuhakmeh** [comment]
So i'm looking at your compiler.js file and I notice it is a mix of handlebars and ember js files. How did you create this file initially? Copy and Paste?

**Comment by brian-slate** [comment]
Any movement on this? I would love to use this compiler but it's already out of date :(

**Comment by Myslik** [comment]
This should already be solved in latest NuGet

**Comment by joelkallman** [comment]
I can confirm that this isn't working in the latest NuGet. I am on version 1.5.0-beta1 and I receive the same issue. If I try to update handlebars to 1.0.0, then I get an error from Ember.

I need to be able to define the compiler version as 3 rather than 4.
