### ISSUE TITLE
Unhandled Exception

### ISSUE THREAD

**Issue by Globegitter** [Myslik/csharp-ember-handlebars#6]
Hi,

I am just getting started with ember.js (and don't have too much .net experience for that matter) and I am currently trying to simply build a basic app.
I am using the 1.2.0-beta1 version of your compiler and all I am currently doing is:
bundles.Add(applicationJsBundle); //Has jQuery, ember, router.js etc.
bundles.Add(new Bundle("~/bundles/templates", new EmberHandlebarsBundleTransform())
                .Include("~/Scripts/App/Templates/application.hbs"));

In _Layout.cshtml I have:
@Scripts.Render("~/bundles/templates")
 @Scripts.Render("~/bundles/app")

and when building the app, I get an error on the Scripts.Render line for the templates.
Specifically:
 Method not found: 'System.Collections.Generic.IEnumerable`1<System.IO.FileInfo> System.Web.Optimization.BundleResponse.get_Files()'. 

I can also pint the stack trace if that helps. I have been trying for some time now to fix this bug, but no luck. I don't know if this here is the best place to ask about that issue, but hope you might be able to help out.
Cheers

**Comment by Globegitter** [comment]
I think I sort of fixed the issue. Seemed to have to do with the 1.1.0-alpha of the optimization framework and that it uses VirtualFiles now (+ I forgot something in the code).
Also, would it be possible to update the examples to the new ember-1.0.0-pre.4 (or the latest nightly), seeing as it has some major changes?

**Comment by Globegitter** [comment]
Ok, I did get it to work with the latest ember build, handlebars.runtime rc2 and jQuery 1.9.1, didn't need much upgrading, though yeah, when I upgrade the nuget to the 1.2.0-beta I am getting an error again because of the newer version of the optimization framework. I kinda made a fix for that, but don't know if it is a great solution.
In any case, I will fork the code and make a merge request for just the updated js files

**Comment by Myslik** [comment]
I have fixed the issue in the latest commit. ExampleWebAPI project should now be fully working.

**Comment by electricgraffitti** [comment]
Can either of you guys elaborate a little on what the exact problem is? I grabbed the latest beta nuget package and I too am having the same error? Any pointer would be great. Thanks

**Comment by Globegitter** [comment]
You can see in that project how I ended up doing it:
https://github.com/OccupOS/OccupOS/tree/master/OccupOSMonitor
as well as:
https://github.com/OccupOS/OccupOS/tree/master/OccupOSMonitor/OccupOSMonitor/App_Start
I included the Ember.Handlebars project and linked to it. Might not be the best way, but I spent quite some time trying to fix everything, that I took the first solution that I got working.

**Comment by electricgraffitti** [comment]
I dont know that this is a good way to handle it. I dont want to have to include a project to get something to work. The nuget package should just work. 

Any chance of a fix?

**Comment by Myslik** [comment]
I will upload updated NuGet as soon as possible. Still wrestling with recovery after broken PC.

**Comment by electricgraffitti** [comment]
Awesome. Thanks man

**Comment by Myslik** [comment]
NuGet updated.

**Comment by electricgraffitti** [comment]
Awesome.. Thanks man!

On Apr 5, 2013, at 5:07 AM, Premysl Krajcovic notifications@github.com wrote:

> NuGet updated.
> 
> —
> Reply to this email directly or view it on GitHub.

Bob Hanson . Co-Owner
Cube2Media LLC.
Web and Mobile Software Development
Salt Lake City Branch - 801.381.4974
bob@cube2media.com
www.cube2media.com
