### ISSUE TITLE
Ember.Handlebars not working with latest Handlebars

### ISSUE THREAD

**Issue by Globegitter** [Myslik/csharp-ember-handlebars#8]
After updating to Handlebars rc3 I am getting this error:
uncaught exception: Template was precompiled with an older version of Handlebars than the current runtime. Please update your precompiler to a newer version (>= 1.0.0-rc.3) or downgrade your runtime to an older version (<= 1.0.rc.2).

Any chance you can update the project? For the meantime I am just switching back to rc2, so it is not too urgent. Th support is really appreciated

**Comment by Myslik** [comment]
Sure I will release the update for new Handlebars version. I hope the new version will work for older handlebars :smile:

**Comment by korczis** [comment]
so how it look with this? I can not wait ..

**Comment by Globegitter** [comment]
Any update on this? Anything I can help?

**Comment by Myslik** [comment]
I thought I released an update already. When I fix my notebook I will push it.

**Comment by Globegitter** [comment]
Not that I want to be pushy or anything, but just a little reminder about the update. Your work is really appreciated and helps really out in our project. Btw, this should also just work with other services such as ServiceStack right?
Thanks again.
